In [2]:
#Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
print(np.all(x))
x = np.array([0, 1, 2, 3])
print(x)
print(np.all(x))

[1 2 3 4]
True
[0 1 2 3]
False


In [3]:
#Write a NumPy program to test whether any of the elements of a given array is non-zero
import numpy as np
x = np.array([1, 0, 0, 0])
print(x)
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(x)
print(np.any(x))

[1 0 0 0]
True
[0 0 0 0]
False


In [4]:
#Create an identity matrix of dimension 4-by-4
x = np. zeros((4, 4))
x[::2, 1::2] = 1.
x[1::2, ::2] = 1.
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [5]:
#Convert a 1-D array to a 3-D array
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
#Convert all the elements of a numpy array from float to integer datatype
ar = np.reshape(ar, (2, 2, 3))
print('3D Numpy array:')
print(ar)

3D Numpy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
##Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
x = np.random.random((10,10))##Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.74662858 0.52646742 0.06181372 0.73395035 0.19460347 0.53302532
  0.61800992 0.50983208 0.79902422 0.13666888]
 [0.39379462 0.47616539 0.51902152 0.90548356 0.29273248 0.87989072
  0.92066522 0.44931335 0.82710858 0.57956211]
 [0.69854961 0.84611653 0.77267809 0.64563309 0.76073353 0.58714642
  0.85899655 0.20419719 0.54936038 0.3282035 ]
 [0.61440524 0.56053337 0.19398115 0.72506274 0.27448461 0.40334219
  0.09283288 0.88479238 0.61934654 0.53932791]
 [0.64888277 0.53576534 0.70784304 0.92522757 0.16022293 0.31715088
  0.23717905 0.42155805 0.55516297 0.1047668 ]
 [0.48179009 0.30820482 0.51423983 0.95322323 0.6712073  0.01562005
  0.84027076 0.40542495 0.83301705 0.69951794]
 [0.36465015 0.47886732 0.14114563 0.13833262 0.77793077 0.3789103
  0.47052721 0.53171609 0.87330602 0.78805206]
 [0.6380039  0.39377959 0.4062082  0.31594205 0.40655549 0.28634108
  0.71089276 0.68100174 0.05809139 0.95761906]
 [0.25020208 0.91051712 0.22278949 0.54225459 0.68605358 0.65013654
  0.75130659 

In [8]:
##Create a random vector of size 30 and find the mean value
x = np.random.random(30)
m = x.mean()
print (m)

0.5067883989580083


In [9]:
##Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = np.diag(1+np.arange(4), k = -1)
print (y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [10]:
##Create a 2d array with 1 on the border and 0 inside
x = np.ones((6,6))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [11]:
##How to add a border (filled with 0's) around an existing array?
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
##Create a 8x8 matrix and fill it with a checkerboard pattern
y = np.zeros ((8,8), dtype=int)
y[1::2, ::2]= 1
y[::2, 1::2] = 1
print (y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:
##Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [14]:
##Create a checkerboard 8x8 matrix using the tile function
array= np.array([[0,1], [1,0]])
S = np.tile(array,(4,4))
print (S)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
##Normalize a 5x5 random matrix
i = np.random.random((5,5))
imax, imin = i.max(), i.min()
i= (i-imin)/(imax-imin)
print (i)

[[0.85947099 0.82103877 0.40243834 0.87732686 0.63329177]
 [0.73356885 0.83995118 0.24256847 1.         0.21072307]
 [0.03183988 0.98931127 0.03094014 0.99088003 0.13220953]
 [0.31922884 0.66790938 0.20597942 0.90966535 0.59665144]
 [0.11407185 0.         0.60707367 0.67168456 0.83486835]]


In [16]:
##Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-16-6826c9df19bf>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [17]:
##Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
r= np.dot(np.ones((5,3)), np.ones((3,2)))
print (r)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [18]:
##Given a 1D array, negate all elements which are between 3 and 8, in place.
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [19]:
##Consider an integer vector Z, which of these expressions are legal? 


In [20]:
##How to round away from zero a float array ?
x = np.random.uniform(-5, +5, 5)
print(np.copysign(np.ceil(np.abs(x)), x))


[1. 2. 1. 4. 3.]


In [21]:
##How to find common values between two arrays?
x = np.arange(0, 20)
y = np.arange(5, 15)
print(np.intersect1d(x, y))

[ 5  6  7  8  9 10 11 12 13 14]


In [22]:
##How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2021-08-16
Today:  2021-08-17
Tomorrow:  2021-08-18


In [23]:
##How to get all the dates corresponding to the month of July 2016?
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [24]:
##.How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(5) * 1
B = np.ones(5) * 2
C = np.ones(5) * 3
print(np.add(A, B, out=B))
print(np.divide(A, 2, out=A))
print(np.negative(A, out=A))
print(np.multiply(A, B, out=A))

[3. 3. 3. 3. 3.]
[0.5 0.5 0.5 0.5 0.5]
[-0.5 -0.5 -0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5 -1.5 -1.5]


In [25]:
##Extract the integer part of a random array of positive numbers using 4 different methods
i = np.random.uniform(0,10,10)

print(i - i%1)
print(i // 1)
print(np.floor(i))
print(i.astype(int))
print(np.trunc(i))

[0. 5. 8. 6. 1. 9. 5. 2. 9. 1.]
[0. 5. 8. 6. 1. 9. 5. 2. 9. 1.]
[0. 5. 8. 6. 1. 9. 5. 2. 9. 1.]
[0 5 8 6 1 9 5 2 9 1]
[0. 5. 8. 6. 1. 9. 5. 2. 9. 1.]


In [27]:
##Create a 5x5 matrix with row values ranging from 0 to 4
s = np.zeros((5,5))
s += np.arange(5)
print(s)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
##Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
##Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [30]:
##Create a random vector of size 10 and sort it
n = np.random.random(10)
n.sort()
print(n)

[0.07336612 0.18723056 0.40180094 0.46635243 0.51472382 0.56106475
 0.63849968 0.65330456 0.85146558 0.95898727]


In [31]:
##.How to sum a small array faster than np.sum?
x = np.arange(10)
np.add.reduce(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
##Consider two random array A and B, check if they are equal
A = np.random.randint(0,1,4)
B = np.random.randint(0,1,4)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

True
True


In [33]:
##Make an array immutable (read-only)
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [39]:
##Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
s = np.sqrt(x ** 2 + y ** 2)
a = np.arctan2(y, x)
print(s)
print(a)

[0.37114579 0.9927034  1.25772777 0.76758472 0.64756218 0.58256291
 0.61900678 0.14979149 0.69656801 0.81172451]
[0.44105966 1.27947886 0.71597724 0.54424304 1.2249785  0.28933833
 1.19077179 0.23377101 1.11280899 0.34369547]


In [34]:
##Create random vector of size 10 and replace the maximum value by 0
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.         0.70063063 0.00293758 0.55542946 0.85736008 0.49045068
 0.49930605 0.83523519 0.42649832 0.05213379]


In [35]:
##Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
p = np.zeros((5,5), [('x',float),('y',float)])
p['x'], p['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(p)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [36]:
##Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [41]:
##Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
a = np.arange(8)
b = a + 0.5
c = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(c))

3638.1636371179666


In [40]:
##Create a structured array representing a position (x,y) and a color (r,g,b)
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-40-ffc9931c539a>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),
